### ISSUE TITLE
Building

### ISSUE THREAD

**Issue by nukeop** [DavidColson/Polybox#3]
Hi, I'm trying to build the project on Linux (not sure if that's possible).
I'm getting this:

```
$ lua premake5.lua                                                                                                                    
lua: premake5.lua:2: attempt to index a nil value (global 'path')
stack traceback:
        premake5.lua:2: in main chunk
        [C]: in ?
```

I don't know the first thing about lua, and I tried both 5.1 and 5.4. I tried googling this message but most answers point to a scoping problem specific to the script, not missing dependencies (might be wrong though).

Would you know what needs to be installed and how to build the project on Linux?

**Comment by DavidColson** [comment]
Sorry for the extraordinarily long time before replying. But you don't need to run this via lua. Just execute the premake.exe file in a command line, giving it the name of the project file you want, such as vs2019, and it will prepare the project for you.

See premake documentation for more details: https://premake.github.io/docs/Using-Premake/

**Comment by nukeop** [comment]
No problem, glad you're still working on this!
